spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - ${service.frontend.url}
              - ${service.gateway.url}
              - "http://localhost:3000"
              - "http://localhost:8090"
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "Authorization,Link,X-Total-Count,X-${spring.application.name}-alert,X-${spring.application.name}-error,X-${spring.application.name}-params, Location"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-service
          uri: ${service.user.url}
          predicates:
            - Path=${service.user.paths.user}
        - id: user-service-auth
          uri: ${service.user.url}
          predicates:
            - Path=${service.user.paths.auth}

        - id: portfolio-service-portfolio
          uri: ${service.portfolio.url}
          predicates:
            - Path=${service.portfolio.paths.portfolio}
        - id: portfolio-service-asset
          uri: ${service.portfolio.url}
          predicates:
            - Path=${service.portfolio.paths.asset}
        - id: portfolio-service-analysis
          uri: ${service.portfolio.url}
          predicates:
            - Path=${service.portfolio.paths.analysis}
        - id: portfolio-service-portfolio_allocation
          uri: ${service.portfolio.url}
          predicates:
            - Path=${service.portfolio.paths.portfolio_allocation}
        - id: portfolio-service-transaction
          uri: ${service.portfolio.url}
          predicates:
            - Path=${service.portfolio.paths.transaction}

# Service URLs and paths configuration
service:
  user:
    url: http://localhost:8081
    paths:
      user: /api/v1/users/**
      auth: /api/v1/auth/**
  portfolio:
    url: http://localhost:8082
    paths:
      portfolio: /api/v1/portfolio/**
      asset: /api/v1/asset/**
      analysis: /api/v1/analysis/**
      portfolio_allocation: /api/v1/portfolio-allocation/**
      transaction: /api/v1/transaction/**
  frontend:
    url: http://localhost:5173
  gateway:
    url: http://localhost:8090


# Server configuration
server:
  port: 8090

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO

# Actuator endpoints exposure
management:
  endpoints:
    web:
      exposure:
        include: "health,info"